package adsync

// ContactAttributesAD List of attributes to be retrieved from active directory
var ContactAttributesAD = []string{
	"displayName",
	"distinguishedName",
	"givenName",
	"name",
	"objectGUID",
	"sn",
	"telephoneNumber",
	"whenCreated",
	"whenChanged",
	"cn",
	"company",
	"mail",
	"mailNickname",
	"memberOf",
	"msExchHideFromAddressLists",
	"objectCategory",
	"proxyAddresses",
	"msExchExtensionAttribute20",
	"msExchRequireAuthToSendTo",
}

var contactInsertSQL = `INSERT INTO ADIR_CONTACTS_E (
	DESCRIPTION,
	DISPLAYNAME,
	DISTINGUISHEDNAME,
	GIVENNAME,
	CONTACTNAME,
	OBJECTGUID,
	SN,
	TELEPHONENUMBER,
	WHENCREATED,
	WHENCHANGED,
	CN,
	COMPANY,
	MAIL,
	MAILNICKNAME,
	MEMBEROF,
	MSEXCHHIDEFROMADDRESSLISTS,
	OBJECTCATEGORY,
	PROXYADDRESSES,
	MSEXCHEXTENSIONATTRIBUTE20,
	MSEXCHREQUIREAUTHTOSENDTO,
	EXPORTDATETIME
) VALUES (
	:DESCRIPTION,
	:DISPLAYNAME,
	:DISTINGUISHEDNAME,
	:GIVENNAME,
	:CONTACTNAME,
	:OBJECTGUID,
	:SN,
	:TELEPHONENUMBER,
	:WHENCREATED,
	:WHENCHANGED,
	:CN,
	:COMPANY,
	:MAIL,
	:MAILNICKNAME,
	:MEMBEROF,
	:MSEXCHHIDEFROMADDRESSLISTS,
	:OBJECTCATEGORY,
	:PROXYADDRESSES,
	:MSEXCHEXTENSIONATTRIBUTE20,
	:MSEXCHREQUIREAUTHTOSENDTO,
	:EXPORTDATETIME
)`

var contactTruncate = "TRUNCATE TABLE ADIR_CONTACTS_E"
